name: flutifyscan
description: "Scan your documents."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  camera: ^0.11.1
  path_provider: ^2.1.5
  image_cropper: ^9.1.0
  permission_handler: ^12.0.0+1
  pdf: ^3.11.3
  printing: ^5.14.2
  share_plus: ^11.0.0
  path: ^1.9.1
  provider: ^6.1.5
  shared_preferences: ^2.5.3
  open_file: ^3.5.10
  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/valknut.png
    - assets/blue.png
    - assets/scanner.png

  fonts:
    - family: Flutify
      fonts:
        - asset: assets/fonts/Flutify.otf
